### ISSUE TITLE
[Discussion] Adding `ECGChannelsGroup` to "root/general" 

### ISSUE THREAD

**Issue by weiglszonja** [Defense-Circuits-Lab/ndx_ecg#1]
Hey @Hamidreza-Alimohammadi!

This looks great overall, I would open this for discussing `ECGChannelsGroup` which holds the implanted electrodes and recording channels DynamicTables. The `ECGChannelsGroup` currently extends `NWBContainer` and is being added to the file as `nwbfile.add_analysis()`.

I think it would make sense to  change `ECGChannelsGroup` to extend `pynwb.file.LabMetaData`, that way `ECGChannelsGroup` would be located in `root/general`:

<img width="233" alt="Screenshot 2023-10-27 at 15 47 37" src="https://github.com/Defense-Circuits-Lab/ndx_ecg/assets/24475788/b75563bf-a741-42c3-ad3c-7b2cc6c2b51b">

This doesn't require a lot to change in your code, in  `create_extension_spec.py` you'd just have to add
`ns_builder.include_type('LabMetaData', namespace='core')`
and change NWBGroupSpec for ECGChannelsGroup to:
`neurodata_type_inc='LabMetaData'`

Example:
```python
nwbfile = NWBFile(
    session_description='ECG test-rec session',
    identifier=str(uuid4()),
    session_start_time=datetime.now(tzlocal()),
    experimenter='experimenter',
    lab='DCL',
    institution='UKW',
    experiment_description='',
    session_id='',
)
# define an endpoint main recording device
main_device = nwbfile.create_device(
    name='name_of_the_MRD',  # MRD: main recording device
    description='description_of_the_MRD',
    manufacturer='manufacturer_of_the_MRD'
)

'''
creating an ECG electrodes table
as a DynamicTable
'''
ecg_electrodes_table = DynamicTable(
    name='ecg_electrodes',
    description='info on ECG electrodes'
)

# add relevant columns
ecg_electrodes_table.add_column(
    name='electrode_name',
    description='reference name of the corresponding electrode'
)
ecg_electrodes_table.add_column(
    name='electrode_location',
    description='the location of the corresponding electrode on the body'
)
ecg_electrodes_table.add_column(
    name='electrode_info',
    description='descriptive information on the corresponding electrode'
)

# add electrodes
ecg_electrodes_table.add_row(
    electrode_name='el_0',
    electrode_location='right upper-chest',
    electrode_info='descriptive info'
)
ecg_electrodes_table.add_row(
    electrode_name='el_1',
    electrode_location='left lower-chest',
    electrode_info='descriptive info'
)
ecg_electrodes_table.add_row(
    electrode_name='reference',
    electrode_location='top of the head',
    electrode_info='descriptive info'
)

'''
creating an ECG recording channels table
as a DynamicTable
'''
recording_channels_table = DynamicTable(
    name='recording_channels',
    description='info on ecg recording channels'
)

# add relevant columns
recording_channels_table.add_column(
    name='channel_name',
    description='reference name of the corresponding recording channel'
)
recording_channels_table.add_column(
    name='channel_type',
    description='type of the recording, e.g., single electrode or differential'
)
recording_channels_table.add_column(
    name='electrodes',
    description='descriptive information the corresponding electrode(s)',
)

# add channels
recording_channels_table.add_row(
    channel_name='ch_0',
    channel_type='single',
    electrodes='el_0'
)
recording_channels_table.add_row(
    channel_name='ch_1',
    channel_type='differential',
    electrodes='el_0 and el_1'
)

ecg_device = ECGRecDevice(
    name='name_of_the_ECGRD',
    description='description_of_the_ECGRD',
    manufacturer='manufacturer_of_the_ECGRD',
    filtering='notch-60Hz-analog',
    gain='100',
    offset='0',
    synchronization='taken care of via ...',
    endpoint_recording_device=main_device,
)

# adding the object of ECGRecDevice
nwbfile.add_device(ecg_device)
nwbfile.add_acquisition(ecg_electrodes_table)
nwbfile.add_acquisition(recording_channels_table)

ecg_channels_group = ECGChannelsGroup(
    name='ecg_channels_group',
    group_description='a group to store electrodes and channels table, and linking to ECGRecDevice.',
    electrodes=nwbfile.acquisition["ecg_electrodes"],
    channels=nwbfile.acquisition["recording_channels"],
    recording_device=ecg_device,
)
nwbfile.add_lab_meta_data(ecg_channels_group)

with NWBHDF5IO("test.nwb", mode='w') as io:
    io.write(nwbfile)

with NWBHDF5IO("test.nwb", mode='r', load_namespaces=True) as io:
    nwbfile_in = io2.read()
    print(nwbfile_in.lab_meta_data["ecg_channels_group"])
```

But there is still the question of where to add `ecg_electrodes_table` and `recording_channels_table`, you can see I added them to acquisition, but I wonder why it not works as:

```python
...
ecg_channels_group = ECGChannelsGroup(
    name='ecg_channels_group',
    group_description='a group to store electrodes and channels table, and linking to ECGRecDevice.',
    electrodes=ecg_electrodes_table,
    channels=recording_channels_table,
    recording_device=ecg_device,
)
```

@bendichter thoughts?

**Comment by Hamidreza-Alimohammadi** [comment]
Hi @weiglszonja!
I appreciate your comments,

I totally agree with having the `ecg_electrodes_table` and `recording_channels_table` as acquisitions! Since I was under the assumption that the `NWBFile.acquisition` is mainly used for raw data interfaces, I didn't think that tables of meta-data could be properly stored here too! Better this than going with the `.analysis`, I assume! I'll implement these changes to the readme and tests...

Also, the `lab_meta_data` sounds like a very reasonable solution to store the `ECGChannelsGroup` directly to it's own storage point in an NWBFile. Since the `LabMetaData` itself is extending the `NWBContainer` and Conceptually, the `NWBFile.LabMetaData` is somewhat similar to the `NWBFile.custom_data` that I was wondering about, I'd rather go with this suggestion of yours... 

Regarding the last part of your comment; From what I understood, you're saying that `ecg_electrodes_table` and `recording_channels_table` can not get directly passed as `ECGChannelsGroup` arguments and need to be called from `NWBFile.acquisition`, right?! I gave it a try:
```python
ecg_channels_group = ECGChannelsGroup(
    name='ecg_channels_group',
    group_description='a group to store electrodes and channels table, and linking to ECGRecDevice.',
    electrodes=ecg_electrodes_table,
    channels=recording_channels_table,
    recording_device=ecg_device,
)
```
and it seemed to be working fine in an IO test! and if I'm missing your point here, would appreciate if you correct me...
Thank you again for your comments!

**Comment by weiglszonja** [comment]
Can you try after updating to latest pynwb?

I opened this PR that will fix the failing tests after updating: https://github.com/Defense-Circuits-Lab/ndx_ecg/pull/2

**Comment by weiglszonja** [comment]
if you agree @Hamidreza-Alimohammadi , I think this issue can be closed.
