### ISSUE TITLE
[Discussion] Add fixed columns for electrodes and channels `DynamicTable`

### ISSUE THREAD

**Issue by weiglszonja** [Defense-Circuits-Lab/ndx_ecg#3]
I think it would make sense to have these columns explicitly added to the extension spec:

```
    ecg_electrodes_table = DynamicTable(
        name='electrodes',
        description='info on ECG electrodes'
    )

    # add relevant columns
    ecg_electrodes_table.add_column(
        name='electrode_name',
        description='reference name of the corresponding electrode'
    )
    ecg_electrodes_table.add_column(
        name='electrode_location',
        description='the location of the corresponding electrode on the body'
    )
    ecg_electrodes_table.add_column(
        name='electrode_info',
        description='descriptive information on the corresponding electrode'
    )
```

Similarly for the channels table:

```
    recording_channels_table = DynamicTable(
        name='channels',
        description='info on ecg recording channels'
    )

    # add relevant columns
    recording_channels_table.add_column(
        name='channel_name',
        description='reference name of the corresponding recording channel'
    )
    recording_channels_table.add_column(
        name='channel_type',
        description='type of the recording, e.g., single electrode or differential'
    )
    recording_channels_table.add_column(
        name='electrodes',
        description='descriptive information the corresponding electrode(s)',
    )
```

In this current form these two tables are way too flexible, if you agree that these columns are usually what the users will also define than they can be explicitly added in `create_extension_spec.py` (similar to [here](https://github.com/catalystneuro/ndx-photometry/blob/7ea9d755ceac9524125f50ab528b403b135c4530/src/spec/create_extension_spec.py#L59))

**Comment by Hamidreza-Alimohammadi** [comment]
At first I was thinking that we could leave room for flexibility... Now I think implementing these as defined standards rather than being flexible, would make it more of an standard entity... So I totally agree and I also implemented the new `ECGElectrodes` and `ECGChannels` now, extending `DynamicTable`. Thanks for the suggestion!
